import { Product, FilterOption } from "./types";

export const products: Product[] = [
  // 1. SparkLite 100
  {
    id: "1",
    title: "SparkLite 100",
    price: "$49.00",
    description: "Portable Emergency Light with integrated solar panel.",
    image: "/HomePlus.png",
    badges: [{ text: "10W", color: "green" }],
    ctaText: "View Details",
    category: "Portable Lanterns",
    powerWatts: 10,
    rating: 4.9,
    reviewCount: 320,
    dailyYield: "N/A",
    warranty: "2 Years",
    longDescription:
      "The SparkLite 100 is your reliable companion for off-grid living. Whether you need light for studying at night, navigating dark paths, or keeping your business open after sunset, this durable lantern delivers.",
    whatsIncluded: [
      "1x SparkLite 100",
      "1x USB Charging Cable",
      "1x User Manual",
    ],
    specs: [
      { label: "Battery Life", value: "12 Hours" },
      { label: "Brightness", value: "150 Lumens" },
    ],
    gallery: ["/HomePlus.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 2. PowerHouse 500
  {
    id: "2",
    title: "PowerHouse 500",
    description: "Complete small household kit for lighting and essentials.",
    price: "$599.00",
    image: "/house_illustration.png",
    badges: [{ text: "500W", color: "green" }],
    ctaText: "View Details",
    category: "Home Solar Systems",
    powerWatts: 500,
    rating: 4.8,
    reviewCount: 124,
    dailyYield: "2.0 kWh",
    warranty: "5 Years",
    longDescription:
      "Power your small home with the PowerHouse 500. Perfect for lights, fans, and TV.",
    whatsIncluded: ["Solar Panel", "Battery Unit", "3x LED Bulbs"],
    specs: [
      { label: "Inverter", value: "500W" },
      { label: "Battery", value: "500Wh" },
    ],
    gallery: ["/house_illustration.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 3. EcoGrid Pro
  {
    id: "3",
    title: "EcoGrid Pro",
    description: "Industrial-grade battery backup for business continuity.",
    price: "$4,250.00",
    image: "/eco_grid.png",
    badges: [{ text: "5kW", color: "green" }],
    ctaText: "View Details",
    category: "Business Continuity",
    powerWatts: 5000,
    rating: 5.0,
    reviewCount: 45,
    dailyYield: "20 kWh",
    warranty: "10 Years",
    longDescription:
      "Keep your business running during outages with the EcoGrid Pro. Heavy duty performance.",
    whatsIncluded: ["5kW Inverter", "5kWh Battery", "Mounting Kit"],
    specs: [
      { label: "Output", value: "5kW" },
      { label: "Capacity", value: "5kWh" },
    ],
    gallery: ["/eco_grid.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 4. FamilyLink+
  {
    id: "4",
    title: "FamilyLink+",
    description: "Off-grid solution for growing family homes.",
    price: "$1,899.00",
    image: "/family_link.png",
    badges: [{ text: "2kW", color: "green" }],
    ctaText: "View Details",
    category: "Home Solar Systems",
    powerWatts: 2000,
    rating: 4.7,
    reviewCount: 89,
    dailyYield: "8.0 kWh",
    warranty: "7 Years",
    longDescription:
      "Energy independence for the whole family. Run your fridge, TV, and lights.",
    whatsIncluded: ["2kW Inverter", "2.5kWh Battery", "4x Panels"],
    specs: [
      { label: "Solar Array", value: "1.2kWp" },
      { label: "Storage", value: "2.5kWh" },
    ],
    gallery: ["/family_link.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 5. SparkGo 200
  {
    id: "5",
    title: "SparkGo 200",
    description: "Rugged portable solar generator for adventure.",
    price: "$245.00",
    image: "/spark_go.png",
    badges: [{ text: "200W", color: "green" }],
    ctaText: "View Details",
    category: "Portable Lanterns",
    powerWatts: 200,
    rating: 4.6,
    reviewCount: 56,
    dailyYield: "N/A",
    warranty: "1 Year",
    longDescription:
      "Power on the go. Perfect for camping or charging devices anywhere.",
    whatsIncluded: ["SparkGo 200 Unit", "Portable Panel"],
    specs: [
      { label: "Capacity", value: "200Wh" },
      { label: "Weight", value: "3kg" },
    ],
    gallery: ["/spark_go.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 6. TitanCell X
  {
    id: "6",
    title: "TitanCell X",
    description: "High-capacity storage for agricultural or industrial use.",
    price: "$8,500.00",
    image: "/titan_cell.png",
    badges: [{ text: "10kW", color: "green" }],
    ctaText: "View Details",
    category: "Industrial Storage",
    powerWatts: 10000,
    rating: 5.0,
    reviewCount: 12,
    dailyYield: "N/A",
    warranty: "15 Years",
    longDescription:
      "Massive storage for heavy loads. 10kW output for industrial machinery.",
    whatsIncluded: ["TitanCell Unit", "Cabling"],
    specs: [
      { label: "Capacity", value: "14kWh" },
      { label: "Max Output", value: "10kW" },
    ],
    gallery: ["/titan_cell.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 7. HomePlus Classic
  {
    id: "7",
    title: "HomePlus Classic",
    description: "Reliable solar lighting for everyday use.",
    price: "$120.00",
    image: "/HomePlus.png",
    badges: [{ text: "50W", color: "blue" }],
    ctaText: "View Details",
    category: "Home Solar Systems",
    powerWatts: 50,
    rating: 4.5,
    reviewCount: 10,
    dailyYield: "N/A",
    warranty: "2 Years",
    longDescription: "Basic solar home system for lighting and phone charging.",
    whatsIncluded: ["Panel", "Battery Hub", "2x Bulbs"],
    specs: [],
    gallery: ["/HomePlus.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 8. HomePlus Pro
  {
    id: "8",
    title: "HomePlus Pro",
    description: "Advanced lighting and charging for the whole family.",
    price: "$350.00",
    image: "/HomePlus_pro.png",
    badges: [{ text: "150W", color: "blue" }],
    ctaText: "View Details",
    category: "Home Solar Systems",
    powerWatts: 150,
    rating: 4.8,
    reviewCount: 22,
    dailyYield: "N/A",
    warranty: "3 Years",
    longDescription: "Upgrade to the Pro for more lights and faster charging.",
    whatsIncluded: ["Larger Panel", "High Capacity Hub", "4x Bulbs"],
    specs: [],
    gallery: ["/HomePlus_pro.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 9. Solar TV Bundle
  {
    id: "9",
    title: "Solar TV Bundle",
    description: "Entertainment package with 24 inch solar TV.",
    price: "$450.00",
    image: "/tv.png",
    badges: [{ text: "TV Included", color: "purple" }],
    ctaText: "View Details",
    category: "Home Solar Systems",
    powerWatts: 100,
    rating: 4.7,
    reviewCount: 18,
    dailyYield: "N/A",
    warranty: "3 Years",
    longDescription: "Watch your favorite shows powered by the sun.",
    whatsIncluded: ['Solar TV 24"', "System", "Antenna"],
    specs: [],
    gallery: ["/tv.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 10. Solar Fan 18"
  {
    id: "10",
    title: 'Solar Fan 18"',
    description: "Keep cool with this standalone solar fan.",
    price: "$85.00",
    image: "/Solar_fan.png",
    badges: [{ text: "Cooling", color: "orange" }],
    ctaText: "View Details",
    category: "Portable Lanterns",
    powerWatts: 40,
    rating: 4.6,
    reviewCount: 50,
    dailyYield: "N/A",
    warranty: "1 Year",
    longDescription: "Beat the heat with our solar rechargeable fan.",
    whatsIncluded: ["Fan", "Panel"],
    specs: [],
    gallery: ["/Solar_fan.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 11. Business Starter Kit
  {
    id: "11",
    title: "Business Starter Kit",
    description: "Essentials for small shop owners.",
    price: "$900.00",
    image: "/house_illustration.png",
    badges: [{ text: "1kW", color: "green" }],
    ctaText: "View Details",
    category: "Business Continuity",
    powerWatts: 1000,
    rating: 4.9,
    reviewCount: 5,
    dailyYield: "4 kWh",
    warranty: "5 Years",
    longDescription: "Start your solar powered business today.",
    whatsIncluded: ["1kW System", "Installation Guide"],
    specs: [],
    gallery: ["/house_illustration.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
  // 12. Industrial backup L
  {
    id: "12",
    title: "Industrial backup L",
    description: "Large scale storage for factories.",
    price: "$15,000.00",
    image: "/titan_cell.png",
    badges: [{ text: "20kW", color: "green" }],
    ctaText: "View Details",
    category: "Industrial Storage",
    powerWatts: 20000,
    rating: 5.0,
    reviewCount: 2,
    dailyYield: "N/A",
    warranty: "20 Years",
    longDescription: "Ultimate reliability for large scale operations.",
    whatsIncluded: ["20kW Unit", "Support"],
    specs: [],
    gallery: ["/titan_cell.png"],
    reviews: [],
    faqs: [],
    howItWorks: [],
  },
];

export const filterOptions: FilterOption[] = [
  { id: "all", label: "All Products", active: true },
  { id: "portable", label: "Portable Power", active: false },
  { id: "residential", label: "Residential Systems", active: false },
  { id: "commercial", label: "Commercial Solar", active: false },
  { id: "accessories", label: "Accessories", active: false },
];
